FROM zoomulus/tomcat7
RUN mkdir -p /var/lib/tomcat7/webapps/eureka \
	&& curl -o /var/lib/tomcat7/webapps/eureka/eureka-server-1.3.1.war http://repo1.maven.org/maven2/com/netflix/eureka/eureka-server/1.3.1/eureka-server-1.3.1.war

